platform :ios, '8.0'

target 'BetterTextFieldExample' do
  use_frameworks!

  pod 'BetterTextField', :path => '~/Documents/Workspace/BetterTextField'
  pod 'IQKeyboardManager'
  pod "TouchVisualizer", '~>1.4.0'
end
